<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email','username', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }

    public function profile()
    {
        return $this->hasOne(Profile::class);
    }

    public function posts()
    {
        return $this->hasMany(Post::class)->orderBy('created_at','desc');
    }

    public function items()
    {
        return $this->hasMany(Item::class)->orderBy('created_at','desc');
    }

    public function publisher(){
        return $this->hasMany(Publisher::class)->orderBy('created_at','desc');
    }

    public function suppliers(){
        return $this->hasMany(Supplier::class)->orderBy('created_at','desc');
    }

    public function purchase_master(){
        return $this->hasMany(PurchaseMaster::class);
    }

    public function following()
    {
        return $this->belongsToMany(Profile::class);
    }

    public function company_info()
    {
        return $this->belongsTo(CompanyInfo::class,'company_infos_id','id');
    }
}
